//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDA377BVT17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int orderdetails_Id { get; set; }
        public int quantity { get; set; }
    
        public virtual Products Product { get; set; }
        public virtual Orders Order { get; set; }
    }
}
