//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDA377BVT17
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayMethods
    {
        public int method_Id { get; set; }
        public string method_name { get; set; }
        public string method_properties { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
